[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.runtime]
nixPkgs = ['python3']

[start]
cmd = "python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
